### ISSUE TITLE
Enabling xnnpack feature leads to runtime crashes

### ISSUE THREAD

**Issue by Manuel030** [ebraraktas/tflitec-rs#27]
Hi, 

on `x86_64-unknown-linux-gnu` enabling xnnpack support leads to runtime crashes: `failed to create the interpreter`. Do you have any idea why?

**Comment by ebraraktas** [comment]
I have no idea. Do you see any errors reported by tensorflow lite itself (not this rust wrapper)?

**Comment by Manuel030** [comment]
Unfortunately not much is reported. The only thing from tensorflow that is logged is:

`INFO: Created TensorFlow Lite XNNPACK delegate for CPU.`

Which is good news I guess. That's why I wonder why the creation of the Interpreter fails.

**Comment by Manuel030** [comment]
Is it possible to control the logging behavior of tensorflow?

**Comment by ebraraktas** [comment]
That could be possible by setting custom error reporter. I will check that, but first can you try official benchmark tool first :

https://www.tensorflow.org/lite/performance/measurement#native_benchmark_binary

Please pass `--use_xnnpack=true`.

**Comment by Manuel030** [comment]
Thank you, this also results in a failure. We can rule out  that the issue is with the Rust bindings.

**Comment by ebraraktas** [comment]
I think we can close this issue, then. If you think I can fix it in this crate, you can reopen.
